### ISSUE TITLE
Reading posterior from TESS

### ISSUE THREAD

**Issue by burbrink** [afmagee/ACDC#2]
Hi Everyone,

This is an incredible program and very well written tutorial. In Section 7 you describe estimating the congruence class from the posterior using RevBayes. I was wondering if you had a similar function that you use for RevBayes, read.RevBayes(), but designed for TESS outputs? If not, do you have a description of how you would do this?

Thanks so much!

Frank

**Comment by kopperud** [comment]
Hi Frank

Thank you for your interest. The `read.RevBayes()` function can also read data frames. So, we can use the TESS output and construct a data frame. If you run the TESS part of the tutorial (section 8.2), you receive the results in the `tess.output` object. I will assume you have something similar

Below I have a suggestion on how to munge the data to read it with `read.RevBayes`.

```r
library(TESS)
library(ACDC)
library(dplyr)
library(tibble)

sp <- as_tibble(tess.output$`speciation rates`)
## Reverse the column order of the TESS output, since TESS is parameterized 
## where t=0 at the root, and t increasing toward present
sp <- sp[, order(ncol(sp):1)]
## Name the columns
names(sp) <- paste0("speciation_rate.",seq_along(names(sp)))

## Equivalent for extinction rate
ex <- as_tibble(tess.output$`extinction rates`)
ex <- ex[, order(ncol(ex):1)]
names(ex) <- paste0("extinction_rate.",seq_along(names(ex)))

## Assemble data frame
df <- bind_cols(sp, ex)

max_t <- max(node.depth.edgelength(tree))

## Read the posterior median
pmedian <- read.RevBayes(df, n_times = 100,
                         max_t = max_t, 
                         summary_type = "median")

## Sample 20 models
posterior <- read.RevBayes(df, n_times = 100,
                           n_samples = 20,
                           max_t = max_t, 
                           summary_type = "none")
```

**Comment by burbrink** [comment]
This worked perfectly. Thanks so much. 

One last question, for the TESS posteriors, do you have advice for the argument MRF.type in the function sample.congruence.class.posterior()?

Thanks again.

Frank

**Comment by afmagee** [comment]
Hi Frank,

That's a great question! 

In spirit as a choice of prior, I would say the HSMRF and the compound poisson process model implemented in TESS (`tess.analysis()`) are similar. Both are flexible and can capture a wide variety of patterns of rates, including large jumps. (For a pure HSMRF model without trends, set `model="MRF"`).

But in practice, I suggest exploring a wide range of alternative models which are reasonable/plausible. This may include models which are similar to the chosen prior, similar to the inferred posterior, or in fact quite different!

As a general guideline, trajectories will be jumpier with `MRF.type=HSMRF` and smoother with `MRF.type=GMRF`. If using exponential/linear/piecewise trends, with a GMRF you're more likely to see smaller departures, while with an HSMRF the departures can be more extreme (and may occasionally lead to a sampled model that bucks the overall increase or decrease specified with `direction`).  Note also that you can turn off the MRF component entirely with `noisy=FALSE` or force it to be consistent with the trends with `monotonic=TRUE`.

You can also call `sample.basic.models()` separately from `sample.congruence.class()` (or `sample.congruence.class.posterior()`) and plot the results to see what sorts of trajectories the different models produce or fine-tune settings.

Hope this helps!

Andy

**Comment by burbrink** [comment]
Andy, thanks a million for the answer. This makes perfect sense. I will try all of these options, though it looks like flat for everything seems the trend no matter what.

Thanks again.

Frank

**Comment by burbrink** [comment]
Hi Bjørn,

I have another quick question regarding the function summarize.posterior(). I wanted to get the actual percentage of flat, decreasing, and increasing percentages for each time slice. Is it possible to output those actual values in a data.frame along with the ggplot? I tried to do this, though my values are slightly different and I assume I may be making an error.

Thanks in advance!

Frank

**Comment by kopperud** [comment]
Hi Frank

There was a bug in the `summarize.posterior(..., return_data = TRUE)` function. I didn't return the correct data frame. I changed it now, if you install the latest version from github (`devtools::install_github("afmagee/ACDC")`) I believe it should work. Thank you for catching this!

As for the coverages you can get those from the data frame that it returns. Something like this

```r
data(primates_ebd_log)

posterior <- read.RevBayes(primates_ebd_log, max_t = 65, n_samples = 20)

samples <- sample.congruence.class.posterior(posterior, 
                                             num.samples = 20,
                                             rate.type = "extinction",
                                             rate0.median = 0.1,
                                             model = "MRF",
                                             max.rate = 1.0)

df <- summarize.posterior(samples, threshold = 0.05, return_data = TRUE)

group_by(df, time) %>% 
  summarize(flat_coverage = mean(as.numeric(direction == 0)),
            increasing_coverage = mean(as.numeric(direction == 1)),
            decreasing_coverage = mean(as.numeric(direction == -1)))

```

Should give  you something like this

```
# A tibble: 99 x 4
    time flat_coverage increasing_coverage decreasing_coverage
   <dbl>         <dbl>               <dbl>               <dbl>
 1 0.328         0.464             0.00476              0.531 
 2 0.985         0.683             0.05                 0.267 
 3 1.64          0.557             0.326                0.117 
 4 2.30          0.55              0.35                 0.1   
 5 2.95          0.662             0.188                0.15  
 6 3.61          0.826             0.05                 0.124 
 7 4.27          0.843             0.0643               0.0929
 8 4.92          0.183             0.8                  0.0167
 9 5.58          0.671             0.25                 0.0786
10 6.24          0.771             0.1                  0.129 
# ... with 89 more rows
```

Notice how there is one less time knot (99 instead of 100 in the example data). This is because the +/-/flat colors are plotted inbetween the original time points.

Hope it helps!
Bjørn

**Comment by burbrink** [comment]
Thanks Bjørn,

You get essentially what I got with my own version of assessing Pp. However, the figure produced over the Pp using TESS and the function sample.congruence.class.posterior() does not show 100% Pp for a decreasing trend, though the calculation using the by_group example you gave above (or formerly my code) says at 2.13 MY this is estimated to be decreasing at 100% Pp.

Here is the plot:
[Rplot.pdf](https://github.com/afmagee/ACDC/files/7953443/Rplot.pdf)

And here is are the first ten times using by_group() (note number 10 at 2.13 MY):
 time flat_coverage increasing_coverage decreasing_coverage
 1 0.112             1                   0                   0
 2 0.336             1                   0                   0
 3 0.560             1                   0                   0
 4 0.784             1                   0                   0
 5 1.01              1                   0                   0
 6 1.23              1                   0                   0
 7 1.46              1                   0                   0
 8 1.68              1                   0                   0
 9 1.90              1                   0                   0
10 2.13              0                   0                   1

I have attached my tree and note I ran this with TESS using the following:
[Tree_Dated_Point_PL_Astral_topology_130.txt](https://github.com/afmagee/ACDC/files/7953460/Tree_Dated_Point_PL_Astral_topology_130.txt)


tess.analysis(tree,
              empiricalHyperPriors = TRUE,
              samplingProbability = 0.96,
              numExpectedRateChanges = 2,
              MAX_ITERATIONS = 1e5,
              MAX_TIME = 2*600*600,
              MIN_ESS = 625,
              dir = "directory")

Thanks again Bjørn.

Frank

**Comment by kopperud** [comment]
I ran the TESS analysis on my machine, and the posterior trends seem fine to me. Maybe there is some settings issue. Not sure I can help further unless I can reproduce the issue on my end, with the same settings etc. If you want you can share your script with me on my email kopperud at protonmail dot com. 

Bjørn

**Comment by burbrink** [comment]
Hey Bjørn,

Thanks for the response.  I got it working on my end. My wrappers failed to update the git version of ACDC. So sorry about that!
